index:
  path: /
  controller: App\Controller\SecurityController::login

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout

dashboard:
  path: /dashboard
  controller: App\Controller\DashboardController::index